<?php
/**
 * Better Wishlist sorter
 *
 * @var $block \Mageplaza\BetterWishlist\Block\Customer\Wishlist\Toolbar
 */
$currentUrl = '';
$ascUrl = '&product_list_dir=asc';
$descUrl = '&product_list_dir=desc';
$sort = $block->getRequest()->getParam('product_list_dir');
$name = $block->getRequest()->getParam('list_order');
//$nameSortUrl = $currentUrl . '?product_list_order=name';
?>

<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="betterwishlist-sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <option value="default"><?= $block->escapeHtml(__('Default')) ?></option>
        <option value="name" <?= $block->escapeHtml($name) == 'name' ? 'selected' : '' ?>><?= $block->escapeHtml(__('Name')) ?></option>
    </select>
    <?php if ($name == 'name') :?>
    <?php if ($sort == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc"
           data-url="<?= $ascUrl ?>">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc"
           data-url="<?= $descUrl ?>">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
    <?php endif; ?>
</div>
