<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="modes">
    <strong class="modes-label" id="modes-label">View as</strong>
    <strong title="Grid" class="modes-mode active mode-grid" data-value="grid">
        <span>Grid</span>
    </strong>
    <a class="modes-mode mode-list" title="List" href="#" data-role="mode-switcher" data-value="list" id="mode-list" aria-labelledby="modes-label mode-list">
        <span>List</span>
    </a>
</div>
